FROM node:dubnium-alpine

# Install codecov
RUN apk add --update py-pip && pip install codecov

# Install latest npm version
RUN npm i --global --silent npm@latest

# Install dependencies
WORKDIR /app
COPY package*.json .npmrc ./
RUN npm i --silent
ENV PATH /app/node_modules/.bin:$PATH

# Set working directory for source code
WORKDIR /app/server
COPY ./ ./

# Run tests
CMD npm run test
