FROM node:dubnium-alpine

# Expose ports
EXPOSE 3000 5858

# Install latest npm version
RUN npm i --global --silent npm@latest

# Install dependencies
WORKDIR /app
COPY package.json package-lock.json .npmrc ./
RUN npm i --no-optional --silent
ENV PATH /app/node_modules/.bin:$PATH

# Set working directory for source code
WORKDIR /app/server

# Start application with live reload
CMD ts-node-dev --poll --inspect=0.0.0.0:5858 -- src/app.ts
