FROM node:erbium-alpine

# Expose ports
EXPOSE 3000 5858

# Install latest npm version
RUN yarn global upgrade --silent yarn@latest

# Install dependencies
RUN mkdir /app && chown node:node /app
WORKDIR /app
USER node
COPY --chown=node:node package.json yarn.lock .yarnrc ./
RUN yarn install --silent
ENV PATH /app/node_modules/.bin:$PATH

# Set working directory for source code
WORKDIR /app/server
COPY --chown=node:node ./ ./

# Start application with live reload
CMD ts-node-dev -r tsconfig-paths/register --transpileOnly --poll --inspect=0.0.0.0:5858 -- index.ts
